import { NextResponse } from "next/server"
import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import { prisma } from "@/lib/prisma"
import { jsPDF } from "jspdf"

interface PageProps {
  params: {
    id: string
  }
}

export async function GET(
  req: Request,
  { params }: PageProps
) {
  try {
    const session = await getServerSession(authOptions)

    if (!session?.user?.id) {
      return NextResponse.json(
        { error: "Unauthorized" },
        { status: 401 }
      )
    }

    const card = await prisma.businessCard.findUnique({
      where: {
        id: params.id,
        userId: session.user.id,
        isDeleted: false,
      },
    })

    if (!card) {
      return NextResponse.json(
        { error: "Card not found" },
        { status: 404 }
      )
    }

    // Track export event
    const ipAddress = req.headers.get("x-forwarded-for") || req.headers.get("x-real-ip") || "unknown"
    const userAgent = req.headers.get("user-agent") || "unknown"
    
    await prisma.cardEvent.create({
      data: {
        cardId: card.id,
        eventType: "export_pdf",
        ipAddress,
        userAgent,
      },
    })

    // Generate PDF
    const pdfBuffer = await generateCardPDF(card)

    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${card.slug}-card.pdf"`,
      },
    })
  } catch (error) {
    console.error("Export PDF error:", error)
    return NextResponse.json(
      { error: "Something went wrong" },
      { status: 500 }
    )
  }
}

async function generateCardPDF(card: any): Promise<Buffer> {
  const doc = new jsPDF({
    orientation: card.aspectRatio === "portrait" ? "p" : "l",
    unit: "mm",
    format: "a4",
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20

  // Get template colors
  const colors = getTemplateColors(card.template)

  // Draw background
  doc.setFillColor(colors.bgStart[0], colors.bgStart[1], colors.bgStart[2])
  doc.rect(0, 0, pageWidth, pageHeight, "F")

  // Add gradient effect (simplified)
  doc.setFillColor(colors.bgEnd[0], colors.bgEnd[1], colors.bgEnd[2])
  doc.rect(0, pageHeight * 0.6, pageWidth, pageHeight * 0.4, "F")

  // Set text color
  doc.setTextColor(colors.text[0], colors.text[1], colors.text[2])

  let y = margin + 20

  // Company Name / Brand Name
  doc.setFontSize(24)
  doc.setFont("helvetica", "bold")
  const displayName = card.brandName || card.companyName
  doc.text(displayName, margin, y)
  y += 15

  // Company Name (if different from brand name)
  if (card.brandName && card.brandName !== card.companyName) {
    doc.setFontSize(14)
    doc.setFont("helvetica", "normal")
    doc.text(card.companyName, margin, y)
    y += 10
  }

  // Designation
  doc.setFontSize(18)
  doc.setFont("helvetica", "bold")
  doc.text(card.designation, margin, y)
  y += 10

  // Area of Business
  if (card.areaOfBusiness) {
    doc.setFontSize(12)
    doc.setFont("helvetica", "normal")
    doc.text(card.areaOfBusiness, margin, y)
    y += 20
  }

  // Add separator line
  doc.setDrawColor(colors.text[0], colors.text[1], colors.text[2])
  doc.setLineWidth(0.5)
  doc.line(margin, y, pageWidth - margin, y)
  y += 15

  // Contact Information
  doc.setFontSize(11)
  doc.setFont("helvetica", "normal")
  const lineHeight = 8

  doc.text(`Official Email: ${card.officialEmail}`, margin, y)
  y += lineHeight

  doc.text(`Phone: ${card.phone}`, margin, y)
  y += lineHeight

  if (card.personalEmail) {
    doc.text(`Personal Email: ${card.personalEmail}`, margin, y)
    y += lineHeight
  }

  if (card.address) {
    const maxWidth = pageWidth - (margin * 2)
    const splitAddress = doc.splitTextToSize(`Address: ${card.address}`, maxWidth)
    doc.text(splitAddress, margin, y)
    y += splitAddress.length * lineHeight
  }

  // GSTIN
  y += 10
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  doc.setTextColor(colors.text[0], colors.text[1], colors.text[2], 0.7)
  doc.text(`GSTIN: ${card.gstin}`, margin, y)

  // Add footer
  doc.setFontSize(8)
  doc.setTextColor(colors.text[0], colors.text[1], colors.text[2], 0.5)
  doc.text(
    `Generated by FormalCard | ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" }
  )

  return Buffer.from(doc.output("arraybuffer"))
}

function getTemplateColors(template: string) {
  const templates: Record<string, any> = {
    "minimal-light": {
      bgStart: [255, 255, 255],
      bgEnd: [248, 250, 252],
      text: [15, 23, 42],
    },
    "corporate-indigo": {
      bgStart: [79, 70, 229],
      bgEnd: [55, 48, 163],
      text: [255, 255, 255],
    },
    "bold-accent": {
      bgStart: [249, 115, 22],
      bgEnd: [220, 38, 38],
      text: [255, 255, 255],
    },
    "monochrome-pro": {
      bgStart: [0, 0, 0],
      bgEnd: [31, 41, 55],
      text: [255, 255, 255],
    },
  }

  return templates[template] || templates["minimal-light"]
}